### PR TITLE
OpenCL implementation

### LINKED ISSUE #11: Move OpenCL kernels from example to module

### PR DESCRIPTION
**Pull request by JimMadge**
Closes #11

### CODE REVIEW

**Comment by gmingas** [comment]
I tried to install locally and run the tests (following the steps in the readme) but got the following error message. Not sure why it fails to do the relative import, have you seen this? Could it be a missing __inti__ file or is it specific to my environment?

```
(env) (base) MAC-ATI0385:Probabilistic-Peridynamics gmingas$ pytest
============================ test session starts ============================
platform darwin -- Python 3.6.7, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /Users/gmingas/projects/Probabilistic-Peridynamics
collected 0 items / 1 error                                                 

================================== ERRORS ===================================
_______________________ ERROR collecting test session _______________________
env/lib/python3.6/site-packages/_pytest/config/__init__.py:495: in _importconftest
    return self._conftestpath2mod[key]
E   KeyError: PosixPath('/Users/gmingas/projects/Probabilistic-Peridynamics/peridynamics/test/conftest.py')

During handling of the above exception, another exception occurred:
env/lib/python3.6/site-packages/_pytest/config/__init__.py:501: in _importconftest
    mod = conftestpath.pyimport()
env/lib/python3.6/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
peridynamics/__init__.py:6: in <module>
    from .model import Model
peridynamics/model.py:3: in <module>
    from neighbour_list import (family, create_neighbour_list, break_bonds,
E   ModuleNotFoundError: No module named 'neighbour_list'

During handling of the above exception, another exception occurred:
env/lib/python3.6/site-packages/py/_path/common.py:383: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
env/lib/python3.6/site-packages/py/_path/common.py:435: in gen
    for p in self.gen(subdir):
env/lib/python3.6/site-packages/py/_path/common.py:424: in gen
    dirs = self.optsort([p for p in entries
env/lib/python3.6/site-packages/py/_path/common.py:425: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
env/lib/python3.6/site-packages/_pytest/nodes.py:506: in _recurse
    ihook = self._gethookproxy(dirpath)
env/lib/python3.6/site-packages/_pytest/nodes.py:487: in _gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
env/lib/python3.6/site-packages/_pytest/config/__init__.py:473: in _getconftestmodules
    mod = self._importconftest(conftestpath)
env/lib/python3.6/site-packages/_pytest/config/__init__.py:509: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: (local('/Users/gmingas/projects/Probabilistic-Peridynamics/peridynamics/test/conftest.py'), (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'neighbour_list'",), <traceback object at 0x7fe030176dc8>))
========================== short test summary info ==========================
ERROR  - _pytest.config.ConftestImportFailure: (local('/Users/gmingas/proj...
!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!
============================= 1 error in 0.17s ==============================
```

**Comment by JimMadge** [comment]
@gmingas Could you print line 3 of `peridynamics/model.py`? It should read

```Python
from .neighbour_list import (...
```

Also, could you look whether the the `neighbour_list` module exists in the install directory. There should be something like `neighbour_list.cpython*.so` there.

**Comment by gmingas** [comment]
The line in the model.py file is as expected. The error message was the older one I had copy-pasted, sorry. I have now updated with the new one which reports line 3 as it is.

I can see the .so file under /Users/gmingas/opt/anaconda3/lib/python3.6/site-packages/peridynamics/:
Screenshot 2020-05-21 at 16 08 28

And also one under build in the local repo dir:
Screenshot 2020-05-21 at 15 49 52 (2)

**Comment by JimMadge** [comment]
@gmingas I have reproduced this and think I understand.

`pip install .` puts the compiled cython modules in your system (or virtual environment) path. However, when you run `pytest` in the repository,  the local `./peridynamics` takes precedent over `/../../peridynamics` and the local repository has no compiled cython modules.

I've found if you make an editable install, `pip install -e .` then the cython modules are left in the repository tree and the tests run. In fact, I already must have found this because the Travis build uses an editable install. Regardless, you should still be able to use the module, you can try running the example `python examples/example1/example.py`.

I'm confused, however, because your second screen shot shows the cython modules in the local path. Could you try this from a clean clone of the repository,
```
pip install cython pytest
pip install -e .
pytest -v
```

**Comment by gmingas** [comment]
@JimMadge the test do run with `pip install -e`. Is there a way to make this work without the `-e`? Or if not, should the README be changed?

Also, running `example.py` fails with the following error, which I think might be related to [this](https://stackoverflow.com/questions/53490248/python-cprofile-error-importing-sortkey-from-pstats) (I am using python 3.6). Although I can see that travis tests with 3.6 and does not fail:
```
Traceback (most recent call last):
  File "examples/example1/example.py", line 10, in <module>
    from pstats import SortKey, Stats
ImportError: cannot import name 'SortKey'
```

**Comment by JimMadge** [comment]
> @JimMadge the test do run with `pip install -e`. Is there a way to make this work without the `-e`? Or if not, should the README be changed?

As far as I know, there is. However, this would mean including all test files in the package. You would then have to do something like `pytest --pyargs peridynamics` **after** moving from the repositories directory to stop the local module being imported.

I'm leaning towards not distributing the tests with the package and updating the instructions. What do you think?

That error looks to be Python3.6 specific. That example isn't run as part of the CI. However, maybe the 3.6 tests should be removed if our example doesn't work with it. 3.6 is quite old now.

**Pull request merged**
